### ISSUE TITLE
Import error in visualize: Can't import visualize_attrs from visualize

### ISSUE THREAD

**Issue by Lucky-Stark-01** [KRLGroup/GraphCW#1]
Hello,

First of all I would like to appreciate your work in the field of predictive modelling with explainability.
I'm trying out your repository for getting visual inspects of substructures that are contributing to the prediction.

I'm getting this error while importing module from visualize from visualize_atttrs.
```
ImportError                               Traceback (most recent call last)
Cell In[22], [line 35](vscode-notebook-cell:?execution_count=22&line=35)
     [33](vscode-notebook-cell:?execution_count=22&line=33) from rdkit import Chem
     [34](vscode-notebook-cell:?execution_count=22&line=34) from torch_geometric.data import Data
---> [35](vscode-notebook-cell:?execution_count=22&line=35) from visualize import visualize_attrs
     [36](vscode-notebook-cell:?execution_count=22&line=36) from dig.xgraph.dataset.mol_dataset import *
     [38](vscode-notebook-cell:?execution_count=22&line=38) from time import sleep

ImportError: cannot import name 'visualize_attrs' from 'visualize'
```
I couldn't find any code file named `visualize` in your repository.

Could you help me to solve this error asap?

**Comment by michelaproietti** [comment]
Hi @Lucky-Stark-01,

Thank you for trying out our repository and spotting this issue. It was indeed a missing file.
Everything should be ok now, but in case of problems do not hesitate to reach out.
